routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

    Route::get('/login', 'SessionController@create')->name('login');
    Route::get('/logout', 'SessionController@destroy');
    Route::get('/forgot-password', 'SessionController@recovery');
    Route::post('/login', 'SessionController@store');
    Route::resource('versement', 'VersementController');
    Route::resource('categorie', 'CategorieController');
    Route::resource('eleve', 'EleveController');
    Route::resource('compte', 'CompteController');
    Route::post('/getmontant/', 'AjaxController@compte_montant')->name('get.montant');
    Route::post('/setacedemic/', 'AnneescolaireController@SetAcademic')->name('set.acedemic');


    Route::group(['prefix'=>'Imprime','namespace'=>'Imprime','as'=>'imprime.'], function () {
        Route::get('/{id}/fiche', 'ImprimeController@getImprime')->name('fiche');
    });

app/Http/Controllers/VersementController.php
<?php 

namespace App\Http\Controllers;

use App\Model\Anneescolaire;
    use App\Model\Categorie;
    use App\Model\Compte;
    use App\Model\Eleve;
    use App\Model\Versement;
    use http\Client\Curl\User;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Auth;
    use MercurySeries\Flashy\Flashy;

    class VersementController extends Controller
{
    private $id_eleve;

    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
      $eleve_vers = Eleve::paginate(5);
      return view('versement.index', compact('eleve_vers'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
    
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
      $this->id_eleve = $id;

      $eleves = Eleve::mine()->whereHas('versement', function ($q){
          return $q->where('eleve_id', $this->id_eleve);
      })->with('versement')->get();

        if((count($eleves) === 0) ===false){

          foreach ($eleves as $item){

              $eleve[]=[
                  'id' => $item->id,
                  'nom' => $item->nom,
                  'prenom' => $item->prenom,
              ];

              $data_montant = 0;

              for ($y =0; $y < count($item->versement); $y++){
                  $data_montant = $item->versement[$y]->montant + $data_montant;
                  $eleve[0]['montant'] = $data_montant;
              }

          }

      }else{

          $eleve = Eleve::mine()->findOrfail($this->id_eleve);

          $compte = Compte::mine()->pluck('libelle','id')->prepend('--Choix Versement--');
          return view('versement.newcreate',compact('eleve','compte'));

       }

      //dd($eleve);

      $compte = Compte::mine()->pluck('libelle','id')->prepend('--Choix Versement--');
      return view('versement.create',compact('eleve','compte'));
    
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update(Request $request,$id)
  {

      //MONTANT DU VERSEMENT => montant       MONTANT DEJA VERSE => montantdverse       DU COMPTE => montantapayer

    $academic = Anneescolaire::mine()
          ->where('platform','academic')
          ->where('active',true)
          ->first();

    $data = [
        'montant' => $request->montant,
        'academic_id' =>  $academic->id,
        'resteapayer' => $request->montantapayer - ($request->montantdverse + $request->montant),
        'user_id'     => Auth::id(),
        'eleve_id'     => $request->id_eleve,
        'compte_id'     => $request->compte_id,
    ];

    if ($versement = Versement::create($data)){

        Flashy::success('Versement Effectué avec succès');
        return redirect()->route('versement.index');
    }

  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {


  }
  
}

?>

resources/views/versement/create.blade.php
@extends('layouts.master')

@section('title') Versement @endsection

@section('subTitle') Attribuer @endsection

@section('content')

    <section class="card">
        <div class="card-header">
            <h4 class="card-title"></h4>
        </div>
        <div class="card-content">

            <div class="card-body">
                {{ Form::model($eleve, ['route'=>['versement.update',$eleve[0]['id']],'method' => 'PUT', 'id' => 'form']) }}
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Nom & Prenom (Eleve)</label>
                            <input type="hidden" name="id_eleve" value="{{$eleve[0]['id']}}" id="id_eleve">
                            {{ Form::text('nom', $eleve[0]['nom'].' '.$eleve[0]['prenom'], ['class'=>'form-control', 'required' => 'required']) }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Type Paiement</label>
                            {{ Form::select('compte_id',$compte,null, ['id' => 'compte','class'=>'form-control', 'required' => 'required']) }}

                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Montant du Compte</label>
                            {{ Form::text('montantapayer', null, ['id' => 'montantapayer','class'=>'form-control', 'required' => true, 'disable' => true]) }}
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Montant Déjà Versé</label>
                            <div id="reste_payer">
                                {{ Form::text('montantdverse',null, ['id' => 'montantdvers','class'=>'form-control', 'disable' => 'true']) }}

                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Reste à Payer</label>
                            {{ Form::number('montant', null, ['id' => 'restepaye','class'=>'form-control', 'required' => true ]) }}
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Montant Versement</label>
                            {{ Form::number('montant', null, ['id' => 'montant_vers','class'=>'form-control', 'required' => true ]) }}
                            <span id="message"></span>

                        </div>
                    </div>

                </div>
                <button id="save" type="submit" class="btn btn-primary btn-icon-split mt-3">
                    <span class="icon text-white-50">
                        <i class="feather icon-save"></i>
                    </span>
                    <span class="text">Enregistrer</span>
                </button>

                {{ Form::close() }}

            </div>
            <div class="col-8">
                <div class="m-2">

                </div>

            </div>

        </div>

        </div>
        </div>
    </section>

@endsection
@section('js')
    <script>

        $(document).ready(function (){

            $("#montant_vers").on('keyup', function () {

                var montant_vers = $(this).val();
                var restepaye = $("#restepaye").val();
                var message = $("#message");
                console.log(restepaye - montant_vers);

                var data = (restepaye - montant_vers);

                if (data == 0){
                    message.removeClass("badge badge-danger badge-info badge-success");
                    message.html("Merci de solder le compte").addClass("badge badge-success");
                    $('#form').find('button[type="submit"]').attr('disabled', false);
                }else if (data > 0){
                    message.removeClass("badge badge-danger badge-info badge-success");
                    message.html("Solde partielle").addClass("badge badge-info");
                    $('#form').find('button[type="submit"]').attr('disabled', false);
                }else if (data < 0) {
                    message.removeClass("badge badge-danger badge-info badge-success");
                    message.html("Attention ce montant est superieur au montant a verser").addClass("badge badge-danger");
                    $('#form').find('button[type="submit"]').attr('disabled', true);
                }


            })

        });

    </script>

    <script>
        $(document).ready(function () {
            $("#compte").on('change',function() {
                var val = $(this).val();
                var id_eleve = $("#id_eleve").val();
                if(val > 0){
                    $("#montantdvers").empty();
                    $("#montantapayer").empty();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        url: "{{ route('get.montant') }}",
                        method: 'post',
                        data:{val:val,id_eleve:id_eleve},
                        dataType: 'json',
                        success: function(result){
                            $("#montantdvers").val(result.montantdverse);
                            $("#montantapayer").val(result.montantapayer);
                            $("#restepaye").val(result.restepaye);

                        },error:function(jqXHR, textStatus){
                            alert('Error.\n'+ jqXHR.responseText);
                        }
                    });
                }
            });
        });

    </script>

@endsection

resources/views/versement/index.blade.php
@extends('layouts.master')

@section('title') Eleves Versement @endsection

@section('subTitle') Attribuer @endsection


@section('content')

    <section class="card">
        <div class="card-header">
            <h4 class="card-title"></h4>
        </div>
        <div class="card-content">

            <div class="card-body">
                @if(create_compte() == true)
                <div class="mb-3">
                    <a class="btn btn-primary" href="{{ route('compte.create') }}">
                        <span><i class="feather icon-plus"></i> Ajout un compte</span>
                    </a>
                </div>
                @endif
                <div class="table-responsive-sm">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>Nom & Prenom</th>
                            <th>Date naissance</th>
                            <th>Nom parent</th>
                            <th>Contact</th>
                            <th>Categorie</th>
                            <th>Groupe Sanguin</th>
                            <th>Email</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($eleve_vers as $item)
                            <tr>
                                <td>{{ $item->nom. ' '. $item->prenom }}</td>
                                <td> {{ $item->date_naissance }}</td>
                                <td> {{ $item->nom_parent }}</td>
                                <td> {{ $item->contact }}</td>
                                <td> {{ $item->categorie->libelle }}</td>
                                <td> {{ $item->groupe_sanguin }}</td>
                                <td> {{ $item->email }}</td>

                                <td class="float-right">
                                    <button type="button"
                                            class="btn btn-icon btn-icon btn-relief-info mr-0 waves-effect waves-light">
                                        <a href="{{ route('versement.edit',$item->id)}}">
                                        <i class="feather icon-link"></i>
                                        Versement
                                        </a>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                        @if(count($eleve_vers) < 1)
                            <tr>
                                <td>Pas d'éleve pour cette Année Academic</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mt-2">
                        {{ $eleve_vers->links() }}
                        {{--<li class="page-item"><a class="page-link" href="#">
                                <i class="feather icon-chevrons-left"></i> Prev
                            </a></li>
                        <li class="page-item active"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">4</a></li>
                        <li class="page-item"><a class="page-link" href="#">5</a></li>
                        <li class="page-item"><a class="page-link" href="#">
                                Next <i class="feather icon-chevrons-right"></i>
                            </a></li>--}}
                    </ul>
                </nav>
            </div>
        </div>
    </section>

@endsection

resources/views/versement/newcreate.blade.php
@extends('layouts.master')

@section('title') Versement @endsection

@section('subTitle') Attribuer @endsection

@section('content')

    <section class="card">
        <div class="card-header">
            <h4 class="card-title"></h4>
        </div>
        <div class="card-content">

            <div class="card-body">
                {{ Form::model($eleve, ['route'=>['versement.update',$eleve->id],'method' => 'PUT']) }}
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Nom & Prenom (Eleve)</label>
                            <input type="hidden" class="form-control" id="identifier" name="id_eleve" value="{{$eleve->id}}">
                            {{ Form::text('nom', $eleve->nom.' '.$eleve->prenom, ['class'=>'form-control', 'required' => 'required']) }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Type Paiement</label>
                            {{ Form::select('compte_id',$compte,null, ['id' => 'compte','class'=>'form-control', 'required' => 'required']) }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Montant du Compte</label>
                            {{ Form::text('montantapayer', null, ['id' => 'montantapayer','class'=>'form-control', 'required' => true, 'disable' => true]) }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Montant Déjà Versé</label>
                            {{ Form::text('montantdverse',null, ['id' => 'montantdvers','class'=>'form-control', 'disable' => 'true']) }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Reste A Payer</label>
                            {{ Form::number('montant', null, ['id' => 'restepaye','class'=>'form-control', 'required' => true ]) }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Montant Versement</label>
                            {{ Form::number('montant', null, ['id' => 'montant_vers','class'=>'form-control', 'required' => true ]) }}
                            <span id="message"></span>

                        </div>
                    </div>
                </div>
                <button id="save" type="submit" class="btn btn-primary btn-icon-split mt-3">
                    <span class="icon text-white-50">
                        <i class="feather icon-save"></i>
                    </span>
                    <span class="text">Enregistrer</span>
                </button>

                {{ Form::close() }}

            </div>
            <div class="col-8">
                <div class="m-2">

                </div>

            </div>

        </div>

        </div>
        </div>
    </section>

@endsection
@section('js')

    <script>

        $(document).ready(function (){

            $("#montant_vers").on('keyup', function () {

                var montant_vers = $(this).val();
                var restepaye = $("#restepaye").val();
                var message = $("#message");
                console.log(restepaye - montant_vers);

                var data = (restepaye - montant_vers);


                if (data == 0){
                    message.removeClass("badge badge-danger badge-info badge-success");
                    message.html("Merci de solder le compte").addClass("badge badge-success");
                    $('#form').find('button[type="submit"]').attr('disabled', false);
                }else if (data > 0){
                    message.removeClass("badge badge-danger badge-info badge-success");
                    message.html("Solde partielle").addClass("badge badge-info");
                    $('#form').find('button[type="submit"]').attr('disabled', false);
                }else if (data < 0) {
                    message.removeClass("badge badge-danger badge-info badge-success");
                    message.html("Attention ce montant est superieur au montant a verser").addClass("badge badge-danger");
                    $('#form').find('button[type="submit"]').attr('disabled', true);
                }


            })

        });

    </script>

    <script>
        $(document).ready(function () {
            $("#compte").on('change',function() {
                var val = $(this).val();
                var id_eleve = $("#id_eleve").val();
                if(val > 0){
                    $("#montantdvers").empty();
                    $("#montantapayer").empty();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        url: "{{ route('get.montant') }}",
                        method: 'post',
                        data:{val:val,id_eleve:id_eleve},
                        dataType: 'json',
                        success: function(result){
                            $("#montantdvers").val(0);
                            $("#montantapayer").val(result.montantapayer);
                            $("#restepaye").val(result.montantapayer);

                        },error:function(jqXHR, textStatus){
                            alert('Error.\n'+ jqXHR.responseText);
                        }
                    });
                }
            });
        });

    </script>

@endsection