routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

    Route::get('/login', 'SessionController@create')->name('login');
    Route::get('/logout', 'SessionController@destroy');
    Route::get('/forgot-password', 'SessionController@recovery');
    Route::post('/login', 'SessionController@store');
    Route::resource('versement', 'VersementController');
    Route::resource('categorie', 'CategorieController');
    Route::resource('eleve', 'EleveController');
    Route::resource('compte', 'CompteController');
    Route::post('/getmontant/', 'AjaxController@compte_montant')->name('get.montant');
    Route::post('/setacedemic/', 'AnneescolaireController@SetAcademic')->name('set.acedemic');


    Route::group(['prefix'=>'Imprime','namespace'=>'Imprime','as'=>'imprime.'], function () {
        Route::get('/{id}/fiche', 'ImprimeController@getImprime')->name('fiche');
    });

app/Http/Controllers/EleveController.php
<?php 

namespace App\Http\Controllers;

    use App\Model\Anneescolaire;
    use App\Model\Categorie;
    use App\Model\Eleve;
    use App\Model\Versement;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\File;
    use Illuminate\Support\Facades\Input;
    use Illuminate\Support\Facades\Storage;
    use MercurySeries\Flashy\Flashy;
    use phpDocumentor\Reflection\Types\Compound;

class EleveController extends Controller{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {

      $eleves = Eleve::paginate(5);
        return view('eleve.index', compact('eleves'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
      $categorie = Categorie::pluck('libelle','id');
    return view('eleve.create', compact('categorie'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {

    $this->validate($request, [
          /*'photo' => 'image|min:3000'*/
      ]);

      $academic = Anneescolaire::mine()
          ->where('platform','academic')
          ->where('active',true)
          ->first();

      // Get image file
      $file = $request->file('photo');
      // Make a image name based on user name and current timestamp
      $filename = str_slug($request->input('nom')).'_' . time() . '.' . $file->getClientOriginalExtension();
      $path = 'photos';

      if(Storage::disk('uploads')->put($path.'/'.$filename,  File::get($file))) {

          $input['categorie_id'] = $request->categorie;
          $input['user_id'] = Auth()->user()->id;
          $input['nom'] = $request->nom;
          $input['prenom'] = $request->prenom;
          $input['date_naissance'] = $request->date_naissance;
          $input['nom_parent'] = $request->nom_parent;
          $input['contact'] = $request->contact;
          $input['email'] = $request->email;
          $input['groupe_sanguin'] = $request->groupe_sanguin;
          $input['photo'] = $filename;
          $input['cm'] = $request->cm;
          $input['academic_id'] = $academic->id;
          $input['pj'] = $request->pj;

          if ($eleve = Eleve::create($input)){

              Flashy::success('Eleve Ajouté avec succès');

              return redirect()->route('eleve.index');
          }else{
              Flashy::error("Erreur c'est produite l'hors de l'ajout");
              return back();
          }
      }


  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id)
  {
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    
  }
  
}

?>

resources/views/eleve/create.blade.php
@extends('layouts.master')

@section('title') Eleves @endsection

@section('subTitle') Create @endsection

@section('css')
    <style>

        .choose_file{
            position:relative;
            display:inline-block;
            border-radius:8px;
            border:#ebebeb solid 1px;
            width:250px;
            padding: 4px 6px 4px 8px;
            font: normal 14px Myriad Pro, Verdana, Geneva, sans-serif;
            color: #7f7f7f;
            margin-top: 2px;
            background:white
        }
        .choose_file input[type="file"]{
            -webkit-appearance:none;
            position:absolute;
            top:0; left:0;
            opacity:0;
        }

    </style>
@endsection
@section('content')

    <section class="card">
        <div class="card-header">
            <h4 class="card-title"></h4>
        </div>
        <div class="card-content">

            <div class="card-body">

                {{ Form::open(['route'=>'eleve.store', 'files'=>true]) }}
               {{-- <div class="col">
                    <div class="form-group">
                        <label for="slug">Photo</label>
                        <input type="text" name="photo" class="form-control" id="photo">
                    </div>
                </div>--}}
                <div class="row">
                    <div class="col float-md-left">
                        <div class="thumbnail" type="file">
                            <img src="{{asset('non_disponible.jpg')}}" id="image_id" height="150" width="135" alt="photo d'identité" onclick="chooseFile();">
                        </div>
                        <div class="choose_file">
                            <span>Choisir une photo</span>
                            <input name="photo" id="fileInput" type="file" required />
                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="col-4">
                        <div class="form-group">
                            <label for="name">Nom</label>
                            <input type="text" name="nom" class="form-control" id="nom" required>
                        </div>
                    </div>
                    <div class="col-4">
                    <div class="form-group">
                            <label for="slug">Prenom </label>
                            <input type="text" name="prenom" class="form-control" id="prenom"  required>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="slug">Date Naissance</label>
                            <input type="date" name="date_naissance" class="form-control" id="date_naissance" required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="slug">Nom Parent</label>
                            <input type="text" name="nom_parent" class="form-control" id="nom_parent">
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="slug">Contact</label>
                            <input type="text" name="contact" class="form-control" id="contact">
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="slug">Email</label>
                            <input type="text" name="email" class="form-control" id="email">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="slug">Groupe Sanguin</label>
                            {{ Form::select('groupe_sanguin', [''=>'---','O-' => 'O-', 'O+' => 'O+','A-' => 'A-' , 'A+' => 'A+','B-' => 'B-', 'B+' => 'B+', 'AB-' => 'AB-', 'AB+' => 'AB+'],null, ['class'=>'form-control', 'required'=>true]) }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="slug">CM</label>
                            <input type="text" name="cm" class="form-control" id="cm">
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="slug">PJ</label>
                            <input type="text" name="pj" class="form-control" id="pj">
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col">
                        <div class="form-group">
                            <label for="slug">Categorie</label>
                            {{ Form::select('categorie',$categorie,null, ['class'=>'form-control', 'required'=>true]) }}
                        </div>
                    </div>

                </div>

                <button id="save" type="submit" class="btn btn-primary btn-icon-split mt-3">
                    <span class="icon text-white-50">
                        <i class="feather icon-save"></i>
                    </span>
                    <span class="text">Enregistrer</span>
                </button>

                {{ Form::close() }}

            </div>
            <div class="col-8">
                <div class="m-2">

                </div>

            </div>

        </div>

        </div>
        </div>
    </section>

@endsection
@section('js')
    <script>
        function chooseFile() {
            $("#fileInput").click();
        }
    </script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image_id').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#fileInput").change(function(){
            readURL(this);
        });
    </script>
@endsection

resources/views/eleve/index.blade.php
@extends('layouts.master')

@section('title') Eleves @endsection

@section('subTitle') Tous @endsection


@section('content')

    <section class="card">
        <div class="card-header">
            <h4 class="card-title"></h4>
        </div>
        <div class="card-content">

            <div class="card-body">

                <div class="mb-3">
                    <a class="btn btn-primary" href="{{ route('eleve.create') }}">
                        <span><i class="feather icon-plus"></i> Ajout un Elève</span>
                    </a>
                </div>

                <div class="table-responsive-sm">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>Nom & Prenom</th>
                            <th>Date naissance</th>
                            <th>Nom parent</th>
                            <th>Contact</th>
                            <th>Categorie</th>
                            <th>Groupe Sanguin</th>
                            <th>Email</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($eleves as $item)
                        <tr>
                            <td>{{ $item->nom. ' '. $item->prenom }}</td>
                            <td> {{ $item->date_naissance }}</td>
                            <td> {{ $item->nom_parent }}</td>
                            <td> {{ $item->contact }}</td>
                            <td> {{ $item->categorie->libelle }}</td>
                            <td> {{ $item->groupe_sanguin }}</td>
                            <td> {{ $item->email }}</td>

                            <td class="float-right">
                                <a href="{{route('imprime.fiche',$item->id)}}"
                                   class="btn btn-icon btn-icon rounded-circle btn-flat-primary mr-0 waves-effect waves-light">
                                    <i class="feather icon-printer"></i>
                                </a>
                                <button type="button"
                                        class="btn btn-icon btn-icon rounded-circle btn-success mr-0 waves-effect waves-light">
                                    <i class="feather icon-target"></i>
                                </button>
                                <button type="button"
                                        class="btn btn-icon btn-icon rounded-circle btn-primary mr-0 waves-effect waves-light">
                                    <i class="feather icon-edit"></i>
                                </button>
                                <button type="button"
                                        class="btn btn-icon btn-icon rounded-circle btn-danger mr-0 waves-effect waves-light">
                                    <i class="feather icon-trash"></i>
                                </button>
                            </td>
                        </tr>
                            @endforeach
                        @if(count($eleves) < 1)
                            <tr>
                                <td>Pas d'éleve pour cette Année Academic</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mt-2">
                        {{ $eleves->links() }}
                        {{--<li class="page-item"><a class="page-link" href="#">
                                <i class="feather icon-chevrons-left"></i> Prev
                            </a></li>
                        <li class="page-item active"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">4</a></li>
                        <li class="page-item"><a class="page-link" href="#">5</a></li>
                        <li class="page-item"><a class="page-link" href="#">
                                Next <i class="feather icon-chevrons-right"></i>
                            </a></li>--}}
                    </ul>
                </nav>
            </div>
        </div>
    </section>

@endsection