routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

    Route::get('/login', 'SessionController@create')->name('login');
    Route::get('/logout', 'SessionController@destroy');
    Route::get('/forgot-password', 'SessionController@recovery');
    Route::post('/login', 'SessionController@store');
    Route::resource('versement', 'VersementController');
    Route::resource('categorie', 'CategorieController');
    Route::resource('eleve', 'EleveController');
    Route::resource('compte', 'CompteController');
    Route::post('/getmontant/', 'AjaxController@compte_montant')->name('get.montant');
    Route::post('/setacedemic/', 'AnneescolaireController@SetAcademic')->name('set.acedemic');


    Route::group(['prefix'=>'Imprime','namespace'=>'Imprime','as'=>'imprime.'], function () {
        Route::get('/{id}/fiche', 'ImprimeController@getImprime')->name('fiche');
    });

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer.blade.php
<div class="sidenav-overlay"></div>
<div class="drag-target"></div>

<!-- BEGIN: Footer-->
<footer class="footer footer-static footer-light">
    <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT &copy; 2019<a class="text-bold-800 grey darken-2" href="#" target="_blank">Ovyoo,</a>All rights Reserved</span><span class="float-md-right d-none d-md-block">Part of Saada Group & Made with<i class="feather icon-heart pink"></i></span>
        <button class="btn btn-primary btn-icon scroll-top" type="button"><i class="feather icon-arrow-up"></i></button>
    </p>
</footer>
<!-- END: Footer-->

resources/views/layouts/header.blade.php
<!-- BEGIN: Header-->
<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>

<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu floating-nav navbar-light navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="navbar-collapse" id="navbar-mobile">
                <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                    <ul class="nav navbar-nav">
                        <li class="nav-item mobile-menu d-xl-none mr-auto">
                            <a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#">
                                <i class="ficon feather icon-menu"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav bookmark-icons">
                        <!-- li.nav-item.mobile-menu.d-xl-none.mr-auto-->
                        <!--   a.nav-link.nav-menu-main.menu-toggle.hidden-xs(href='#')-->
                        <!--     i.ficon.feather.icon-menu-->

                    </ul>
                </div>

                <ul class="nav navbar-nav ">

                    @if (Route::has('login'))

                        @auth

                            <div class="col float-left">
                                <div class="form-group">
                                    <label for="name"><span class="custom-control-indicator">Année Acedemic</span></label>
                                    {{ Form::select('active', list_academic(),null, ['id' => 'academic','class'=>'form-control', 'required' => 'required']) }}
                                    {{--{{ Form::select('active', list_academic() != null ? list_academic() : null, ['class'=>'form-control col-md-12', 'required'=>true ]) }}--}}
                                </div>
                            </div>
                            <li class="dropdown dropdown-user nav-item float-right">
                                <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                                    <div class="user-nav d-sm-flex d-none">
                                        <span class="user-name text-bold-600">{{ Auth::user()->name }}</span>
                                        <span class="user-status">Available</span>
                                    </div>
                                    <span>
                                <img class="round" src="{{ asset('app-assets/images/portrait/small/avatar-s-11.png') }}"
                                     alt="avatar" height="40" width="40"/>
                            </span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="#">
                                        <i class="feather icon-user"></i> Profile
                                    </a>

                                    <a class="dropdown-item" href="#">
                                        <i class="feather icon-user-plus"></i> Manage Users
                                    </a>
                                    <a class="dropdown-item" href="#">
                                        <i class="feather icon-shield"></i> Manage Roles
                                    </a>

                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item" href="#" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                        <i class="feather icon-power"></i>
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="#" method="POST"
                                          style="display: none;">
                                        @csrf
                                    </form>

                                </div>
                            </li>

                        @else
                            <li class="nav-item d-none d-lg-block">
                                <a class="nav-link" href="{{ route('login') }}">Login</a>
                            </li>

                            @if (Route::has('register'))

                                <li class="nav-item d-none d-lg-block">
                                    <a class="nav-link" href="{{ route('register') }}">Register</a>
                                </li>

                            @endif

                        @endauth

                    @endif

                </ul>
            </div>
        </div>
    </div>
</nav>
@section('js')
    <script>
        $(document).ready(function () {
            $("#academic").on('change',function() {
                var val = $(this).val();
                console.log(val);
                if(val != ''){
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        url: "{{ route('set.acedemic') }}",
                        method: 'post',
                        data:{id:val},
                        dataType: 'json',
                        success: function(result){

                            location.reload(true);

                        },error:function(jqXHR, textStatus){
                            alert('Error.\n'+ jqXHR.responseText);
                        }
                    });
                }
            });
        });

    </script>
@endsection
<!-- END: Header-->

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html class="loading" lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Ouattara Idriss - synderime@gmail.com">

    <title>Cocody Rugby Abidjan Club - @yield('title')</title>

    <link rel="apple-touch-icon" href="{{ asset('app-assets/images/ico/apple-icon-120.png') }}">
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('app-assets/images/ico/favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">

    @include('layouts.styles')


</head>
<!-- END: Head-->


<!-- BEGIN: Body-->
<body class="vertical-layout vertical-menu-modern 2-columns  navbar-floating footer-static   menu-collapsed"
      data-open="click" data-menu="vertical-menu-modern" data-col="2-columns">

@include('layouts.sidebar')

<!-- BEGIN: Content-->
<div class="app-content content">

    @include('layouts.header')


    <div class="content-wrapper">

        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">@yield('title')</h2>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="{{ route('home') }}">Accueil</a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a href="#">@yield('title')</a>
                                </li>
                                <li class="breadcrumb-item active">@yield('subTitle')</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="content-body">
            @yield('content')
        </div>

    </div>

</div>
<!-- END: Content-->

<script>
    window.baseUrl = '{{ url('/') }}'
</script>
@include('layouts.footer')
@include('layouts.scripts')
@include('flashy::message')
</body>

</html>

resources/views/layouts/scripts.blade.php
<!-- BEGIN: Vendor JS-->
<script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>
<!-- BEGIN Vendor JS-->


<!-- BEGIN: Theme JS-->
<script src="{{ asset('app-assets/js/core/app-menu.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/components.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/customizer.min.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/footer.min.js') }}"></script>
<!-- END: Theme JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="{{ asset('app-assets/vendors/js/extensions/jquery.steps.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/forms/validation/jquery.validate.min.js') }}"></script>
<!-- END: Page Vendor JS-->

@yield('js')

<script>

</script>

resources/views/layouts/sidebar.blade.php
<!-- BEGIN: Main Menu-->
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">

    <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item mr-auto">
                <a class="navbar-brand">
                    <div class="brand-logo"></div>
                    <h2 class="brand-text mb-0">CRAC</h2>
                </a>
            </li>
            <li class="nav-item nav-toggle">
                <a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse">
                    <i class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i>
                    <i class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block collapse-toggle-icon primary"
                       data-ticon="icon-disc"></i>
                </a>
            </li>
        </ul>

    </div>

    <div class="shadow-bottom"></div>

    <div class="main-menu-content">

        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

            <li class="navigation-header"><span></span></li>

            <li class="nav-item">
                <a href="{{ route('eleve.index')}}">
                    <i class="feather icon-user-plus"></i>
                    <span class="menu-title" data-i18n="Videos">Eleves</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="{{route('versement.index')}}">
                    <i class="feather icon-dollar-sign"></i>
                    <span class="menu-title" data-i18n="Campaigns">Versement</span>
                </a>
            </li>
            <li class="nav-item has-sub sidebar-group-active">
                <a href="#">
                    <i class="feather icon-corner-left-down"></i>
                    <span class="menu-title" data-i18n="">Comptes</span>
                </a>
                <ul class="menu-content" style="">
                    <li>
                        <a href="{{route('compte.create')}}">
                            <i></i><span class="menu-item" data-i18n="Categorie create">Creation</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{route('compte.index')}}">
                            <i></i><span class="menu-item" data-i18n="Categorie affiche">Affiche compte</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item has-sub sidebar-group-active">
                <a href="#">
                    <i class="feather icon-zap"></i>
                    <span class="menu-title" data-i18n="">Categorie</span>
                </a>
                <ul class="menu-content" style="">
                    <li>
                        <a href="{{route('categorie.create')}}">
                            <i></i><span class="menu-item" data-i18n="Categorie create">Creation</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{route('categorie.index')}}">
                            <i></i><span class="menu-item" data-i18n="Categorie affiche">Affiche categorie</span>
                        </a>
                    </li>
                </ul>
            </li>



            {{--<li class="nav-item">
                <a href="#">
                    <i class="feather icon-pie-chart"></i>
                    <span class="menu-title" data-i18n="Analytics">Analytics</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="#">
                    <i class="feather icon-user-x"></i>
                    <span class="menu-title" data-i18n="Leads">Leads</span>
                </a>
            </li>

            <hr>

            <li class="nav-item">
                <a href="#">
                    <i class="feather icon-activity"></i>
                    <span class="menu-title" data-i18n="Training">Training</span>
                </a>
            </li>


            <li class="nav-item">
                <a href="#">
                    <i class="feather icon-life-buoy"></i>
                    <span class="menu-title" data-i18n="Help Center">Help Center</span>
                </a>
            </li>

            <li class="nav-item has-sub sidebar-group-active">
                <a href="#">
                    <i class="feather icon-zap"></i>
                    <span class="menu-title" data-i18n="">Integrations</span>
                </a>
                <ul class="menu-content" style="">
                    <li>
                        <a href="#">
                            <i></i><span class="menu-item" data-i18n="Amazon API">Amazon API</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i></i><span class="menu-item" data-i18n="eBay API">eBay API</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i></i><span class="menu-item" data-i18n="Aliexpress API">Aliexpress API</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i></i><span class="menu-item" data-i18n="walmart">Walmart API</span>
                        </a>
                    </li>

                </ul>
            </li>

            <hr>

            <li class="nav-item">
                <a href="#">
                    <i class="feather icon-users"></i>
                    <span class="menu-title" data-i18n="Team Manager">Team Manager</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="#">
                    <i class="feather icon-message-square"></i>
                    <span class="menu-title" data-i18n="Manage Clients">Manage Clients</span>
                </a>
            </li>--}}

        </ul>

    </div>

</div>
<!-- END: Main Menu-->

resources/views/layouts/styles.blade.php
<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/vendors.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/forms/select/select2.min.css') }}">
<!-- END: Vendor CSS-->

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/bootstrap.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/bootstrap-extended.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/colors.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/components.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/themes/dark-layout.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/themes/semi-dark-layout.css') }}">

<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/core/menu/menu-types/vertical-menu.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/core/colors/palette-gradient.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/animate/animate.min.css') }}">
<!-- END: Page CSS-->

<!-- BEGIN: Custom CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/style.css') }}">
<!-- END: Custom CSS-->


@yield('css')

<style>

</style>